export const REDUX_ROUTES = {
    GENERAL: {
        PRAYERS_FETCH_REQUEST: "PRAYERS_FETCH_REQUEST",
        PRAYERS_FETCH_SUCCESS: "PRAYERS_FETCH_SUCCESS",
        PRAYERS_FETCH_FAILURE: "PRAYERS_FETCH_FAILURE",

        PRAYERS_SET_REQUEST: "PRAYERS_SET_REQUEST",
        PRAYERS_SET_SUCCESS: "PRAYERS_SET_SUCCESS",
        PRAYERS_SET_FAILURE: "PRAYERS_SET_FAILURE",
    },
    USERS: {
        USERS_FETCH_REQUEST: "USERS_FETCH_REQUEST",
        USERS_FETCH_SUCCESS: "USERS_FETCH_SUCCESS",
        USERS_FETCH_FAILURE: "USERS_FETCH_FAILURE",

        USER_SET_REQUEST: "USER_SET_REQUEST",
        USER_SET_SUCCESS: "USER_SET_SUCCESS",
        USER_SET_FAILURE: "USER_SET_FAILURE",
    },
    EVENTS: {
        EVENTS_FETCH_REQUEST: "EVENTS_FETCH_REQUEST",
        EVENTS_FETCH_SUCCESS: "EVENTS_FETCH_SUCCESS",
        EVENTS_FETCH_FAILURE: "EVENTS_FETCH_FAILURE",

        EVENT_SET_REQUEST: "EVENT_SET_REQUEST",
        EVENT_SET_SUCCESS: "EVENT_SET_SUCCESS",
        EVENT_SET_FAILURE: "EVENT_SET_FAILURE",
    },
    POSTS: {
        POSTS_FETCH_REQUEST: "POSTS_FETCH_REQUEST",
        POSTS_FETCH_SUCCESS: "POSTS_FETCH_SUCCESS",
        POSTS_FETCH_FAILURE: "POSTS_FETCH_FAILURE",

        POST_SET_REQUEST: "POST_SET_REQUEST",
        POST_SET_SUCCESS: "POST_SET_SUCCESS",
        POST_SET_FAILURE: "POST_SET_FAILURE",
    },
    AUTH:{
        SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
        SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
        SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

        CREATE_REQUEST: "CREATE_REQUEST",
        CREATE_SUCCESS: "CREATE_SUCCESS",
        CREATE_FAILURE: "CREATE_FAILURE",

        SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
        SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    },
}

export const NETWORKING = {
    MAX_RETRIES: 5,
    WAIT_TIME: 5000
}